version: '3.8'

services:
  app:
    container_name: grade_service_app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CONFIG_FILE: "config.yaml"
    entrypoint: "./entrypoint.sh"
    volumes:
      - ./src:/usr/src/app/src/
    networks:
      - grade_service_network
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

  redis:
    container_name: grade_service_redis
    image: redis:7.0.8-alpine
    expose:
      - 6379
    ports:
      - "6379:6379"
    networks:
      - grade_service_network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 20s
      retries: 100

  postgres:
    container_name: grade_service_postgres_db
    image: postgres:15.1-alpine
    volumes:
      - grade_service_postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=grade_service
      - POSTGRES_USER=grade_service
      - POSTGRES_PASSWORD=grade_service
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - grade_service_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U grade_service" ]
      interval: 5s
      timeout: 20s
      retries: 100

networks:
  grade_service_network:
    name: grade_service_network

volumes:
  grade_service_postgres_data:
