version: '3.8'

services:
  test_menu_app:
    container_name: test_menu_app
    build:
      context: .
      dockerfile: DockerfileTest
    environment:
      CONFIG_FILE: "config.test.yaml"
    command: "pytest -vv"
    networks:
      - test_menu_network
    depends_on:
      test_menu_postgres_db:
        condition: service_healthy

  test_menu_postgres_db:
    container_name: test_menu_postgres_db
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    expose:
      - 15432
    networks:
      - test_menu_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test" ]
      interval: 5s
      timeout: 20s
      retries: 100

networks:
  test_menu_network:
    external:
      name: menu_network
