version: '3.8'

services:
  app:
    container_name: test_salary_ticket_service_app
    platform: linux/amd64  # Specify the desired platform
    build:
      context: .
      dockerfile: DockerfileTest
    environment:
      CONFIG_FILE: "config.test.yaml"
    command: "pytest -vv"
    networks:
      - test_salary_ticket_service_network
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: test_salary_ticket_service_postgres
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    expose:
      - 15432
    networks:
      - test_salary_ticket_service_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test" ]
      interval: 5s
      timeout: 20s
      retries: 100

networks:
  test_salary_ticket_service_network:
    external:
      name: test_salary_ticket_service_network
