version: '3.8'

services:
  app:
    container_name: salary_ticket_service_app
    platform: linux/amd64  # Specify the desired platform
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CONFIG_FILE: "config.yaml"
    entrypoint: "./entrypoint.sh"
    volumes:
      - ./src:/usr/src/app/src/
    networks:
      - salary_ticket_service_network
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

  redis:
    container_name: salary_ticket_service_redis
    image: redis:7.0.8-alpine
    expose:
      - 6379
    ports:
      - "6379:6379"
    networks:
      - salary_ticket_service_network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 20s
      retries: 100

  postgres:
    container_name: salary_ticket_service_postgres
    image: postgres:15.1-alpine
    volumes:
      - salary_ticket_service_postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=salary_ticket_service
      - POSTGRES_USER=salary_ticket_service
      - POSTGRES_PASSWORD=salary_ticket_service
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - salary_ticket_service_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U salary_ticket_service" ]
      interval: 5s
      timeout: 20s
      retries: 100

networks:
  salary_ticket_service_network:
    name: salary_ticket_service_network

volumes:
  salary_ticket_service_postgres_data:
