app:
  project_name: salary-ticket-service
  description: salary-ticket-service project's description
  version: 0.1.0
  api_doc_prefix: /api/v1
  debug: true
  db_exclude_tables: []

test_postgres:
  host: test_menu_postgres_db
  port: 15432
  dbname: test
  user: test
  password: test
