app:
  project_name: salary-ticket-service
  description: salary-ticket-service project's description
  version: 0.1.0
  api_doc_prefix: /api/v1
  debug: true
  db_exclude_tables: []

postgres:
  host: localhost
  port: 5432
  dbname: salary_ticket_service
  user: salary_ticket_service
  password: salary_ticket_service

redis:
  host: localhost
  port: 6379
  db: 0
  encoding: utf-8
  cache_expire_time: 300 # 5 минут
  max_connections: 10
